version: 0.2

env:
  environment: "dev"

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo Installing servless dependencies for tpip-pptx_generator microservice
      - npm install -g serverless@2.52.1
      - echo Finished installing servless dependencies
      - cd pptx_generator
      - echo Installing pptx_generator microservice API dependencies
      - npm install --silent
      - echo Finished installing util microservice API dependencies
  build:
    commands:
      - export AWS_ACCESS_KEY_ID=$KEY
      - export AWS_SECRET_ACCESS_KEY=$VALUE
      - echo Deploying tpip-ms-pptx-gen microservice initiated
      - serverless deploy --s dev
      - echo Deploying tpip-ms-pptx-gen microservice completed
