version: 0.2

env:
  environment: "dev"

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing servless dependencies for tpip-payload_creator microservice
      - npm install -g serverless@2.52.1
      - echo Finished installing servless dependencies
      - cd payload_creator
      - echo Installing payload_creator microservice API dependencies
      - npm install --silent
      - echo Finished installing util microservice API dependencies
  build:
    commands:
      - export AWS_ACCESS_KEY_ID=$KEY
      - export AWS_SECRET_ACCESS_KEY=$VALUE
      - echo Deploying tpip-ms-pptx-payload microservice initiated
      - serverless deploy --s dev
      - echo Deploying tpip-ms-pptx-payload microservice completed
