service: tpip-ms-pptx-gen
projectDir: ../
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.7
  stage: ${file(../env.yml):${opt:stage}.environment}
  region: ${file(../env.yml):${opt:stage}.region}
  environment:
    POC_PPTX_BUCKET: ${file(../env.yml):${opt:stage}.pocPptxBucket}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:ListBucket
          Resource: '*'

custom:
  serverless-offline:
    host: 0.0.0.0
  prune:
    automatic: true
    number: 3
  pythonRequirements:
    dockerizePip: true # make it 'non-linux' when adding to the codepipeline if the proper python version installed in the pipeline
    useDownloadCache: false
    useStaticCache: false
    


functions:
  generate:
    handler: route.generate
    timeout: 900
    events:
      - http:
          cors: true
          method: post
          path: /poc/pptx/generate
    
      

plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-prune-plugin
  - serverless-cloudformation-resource-counter
