service: tpip-ms-pptx-gen
projectDir: ../
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.7
  stage: ${file(../env.yml):${opt:stage}.environment}
  region: eu-west-2
  environment:
    POC_PPTX_BUCKET: ${file(../env.yml):${opt:stage}.pocPptxBucket}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: '*'

custom:
  serverless-offline:
    host: 0.0.0.0
  prune:
    automatic: true
    number: 3

functions:
  generate:
    handler: route.generate
    timeout: 900
    events:
      - http:
          cors: true
          method: post
          path: /poc/pptx/generate

plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-prune-plugin
  - serverless-cloudformation-resource-counter